sonar.projectKey=JobPrep_Group80_questionservice
sonar.projectName=Question Service
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
